### ISSUE TITLE
Incorrect input argument mentioned in documentation

### ISSUE THREAD

**Issue by pratap-akhand** [delphix/virtualization-sdk#200]
Expected Command:
dvp init -n first_plugin -s STAGED -t WINDOWS.

Documented Command:
dvp init -n first_plugin -s STAGED -p WINDOWS.

**Steps to reach the incorrect description**
1. Go to https://developer.delphix.com/Building_Your_First_Plugin/Initial_Setup/
2. Under the section: `Creating a Bare Plugin`,  wrong input argument is mentioned for `dvp init` command. Instead of `-p`, `-t` should be documented.

**Comment by crystalplumage** [comment]
I also notice that the doc section in question says "Our plugin will virtualize simple directory trees on Unix systems."   This matches all of the text, except for this `dvp init` example, which shows a Windows plugin for some reason. 

We should probably change this example from `WINDOWS` to `UNIX` as well for consistency.
