### ISSUE TITLE
Document that removing the password property from a schema param will decrypt all the data in that field on upgrade.

### ISSUE THREAD

**Issue by AleksandrLiber** [delphix/virtualization-sdk#205]
We should add a warning to the documentation that if a schema is modified to remove the password property, the data that was stored in that field will be decrypted and stored as plain text. 
See PYT-1387 in internal Jira

**Comment by nhlien93** [comment]
https://developer.delphix.com/Best_Practices/Sensitive_Data/ maybe add info here?

**Comment by jeffngo** [comment]
I'm going to close this doc request. We already have a note in the docs (`Sensitive_Data.md`) stating:
```
Removing a previously added password property from a field and running a [Data Migration](Glossary.md#data-migration) will expose the password in plaintext.
```
