### ISSUE TITLE
dvp build should support "start hooks run at enable time" flag

### ISSUE THREAD

**Issue by mothslaw** [delphix/virtualization-sdk#228]
Some (but not all) plugins will want users' start hooks to run when VDBs are enabled (and likewise, stop hooks when VDBs are disabled).

There is a feature being added to the engine that will allow plugin artifacts to provide a boolean field (optional), probably to be called `startHooksRunDuringEnable`.  But, `dvp build` will need to support this before plugin authors can benefit from it.

**Comment by crystalplumage** [comment]
Note that this will require a doc change to explain how/why to use this feature.
