### ISSUE TITLE
Update SDK to add SnapshotParametersDefinition in uploaded artifact

### ISSUE THREAD

**Issue by fdrozdowski** [delphix/virtualization-sdk#234]
For the DE component to make the snapshot parameters dynamically generated we need to have the schema of the SnapshotParametersDefinition passed in the artifact that is uploaded.

We're still going to default the schema to:

```
    'snapshotParametersDefinition': {
        'type': 'object',
        'additionalProperties': False,
        'properties': {
            'resync': {
                'type': 'boolean'
            }
        }
    }
```

until the ui is done so that it can take care of other schemas.

Then we'll update the sdk again to expect the schema.json file to have this definition in it.

(Source [PYT-514](https://jira.delphix.com/browse/PYT-514))

**Comment by nhlien93** [comment]
#255
